name: Bug report
description: Report a bug and help improve the plugin
title: "[BUG] Short description of the bug"
labels: bug
assignees: mnaoumov
body:
  - type: markdown
    attributes:
      value: |
        ## Bug report

        > [!WARNING]
        >
        > Both a video and a sample vault are required for bug reproduction. Incomplete, vague, or poorly described bug reports will be closed.
        >
        > The bug report and all attachments (screenshots, videos, sample vaults) must be in English. Exception: the bug is directly related to non-English language usage. Non-English bug reports will be closed.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug. Include any relevant details.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide a step-by-step description.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Notice that '...'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened? Include error messages if available.
    validations:
      required: true
  - type: input
    attributes:
      label: Plugin version
      description: ⚠️ Must be the latest version. If not, explain why above.
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Obsidian version
      description: ⚠️ Must be the latest version. If not, explain why above.
      placeholder: 1.3.2
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      placeholder: Windows 10
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attachments
      description: Attach a video and a sample vault.
      placeholder: Drag and drop files here.
  - type: dropdown
    attributes:
      label: Video
      options:
        - "Not attached. ⚠️ The bug report will be closed if the maintainer is unable to reproduce it without the attachment."
        - "Attached"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Sample vault
      options:
        - "Not attached. ⚠️ The bug report will be closed if the maintainer is unable to reproduce it without the attachment."
        - "Attached"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Bug isolation
      description: Did you verify the bug in isolation from other plugins?
      options:
        - "No, only with other plugins enabled (provide details in the description field). ⚠️ Sample vault required or the bug report will be closed."
        - "Yes, I could reproduce the bug in the vault with only this plugin enabled."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Confirmations
      description: Ensure the following conditions are met
      options:
        - label: I have checked the plugin's GitHub repository and haven't found any similar bugs
          required: true
