name: Feature request
description: Request a feature and help improve the plugin
title: "[FR] Short description of the feature"
labels: enhancement
assignees: mnaoumov
body:
  - type: markdown
    attributes:
      value: |
        ## Feature request

        > [!WARNING]
        >
        > Incomplete, vague, or poorly described requests will be closed.
        >
        > The feature request and all attachments (screenshots, videos, sample vaults) must be in English. Exception: the request is directly related to non-English language usage. Non-English feature requests will be closed.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the feature request. Include any relevant details.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: Describe a scenario where this feature would be useful.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Desired behavior
      description: What do you want to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: What actually happens?
    validations:
      required: true
  - type: input
    attributes:
      label: Plugin version
      description: ⚠️ Must be the latest version. If not, explain why above.
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Obsidian version
      description: ⚠️ Must be the latest version. If not, explain why above.
      placeholder: 1.3.2
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attachments
      description: Attach a video and a sample vault.
      placeholder: Drag and drop files here.
  - type: dropdown
    attributes:
      label: Video
      options:
        - "Not attached. ⚠️ Providing a video helps the maintainer understand the request and speeds up implementation."
        - "Attached"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Sample vault
      options:
        - "Not attached. ⚠️ Providing a sample vault helps the maintainer understand the request and speeds up implementation."
        - "Attached"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Confirmations
      description: Ensure the following conditions are met
      options:
        - label: I have checked the plugin's GitHub repository and haven't found any similar feature requests
          required: true
